spring.application.name=batshop
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/batshop?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.file-size-threshold=2KB
server.tomcat.max-part-count=500

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huydn2.ce190894@gmail.com
spring.mail.password=fxcnkbmdhrqmsvzh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cho phép hi?n th? message l?i
server.error.include-message=always
# Cho phép hi?n th? ???ng d?n b? l?i và các l?i binding
server.error.include-binding-errors=always
# Cho phép hi?n th? Stack Trace (chi ti?t các dòng code gây l?i)
server.error.include-stacktrace=always